# Generated by Django 5.2.8 on 2025-11-12 15:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Policy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(help_text='details about policy', max_length=500)),
                ('monthly_premium', models.DecimalField(decimal_places=2, help_text='premium pay per month', max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('deductible', models.DecimalField(decimal_places=2, help_text='amount user have to pay', max_digits=10)),
                ('max_coverage_limit', models.DecimalField(decimal_places=2, help_text='maximum amout company will pay', max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Customer_Policy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('status', models.CharField(choices=[('ACTIVE', 'ACTIVE'), ('EXPIRE', 'EXPIRED'), ('CANCELLED', 'CANCELLED')], help_text='Contract status', max_length=10)),
                ('user', models.ForeignKey(help_text='customer belongs to this policy', on_delete=django.db.models.deletion.CASCADE, related_name='customer_policies', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Claim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('incident_date', models.DateTimeField(help_text='incident date and time')),
                ('status', models.CharField(choices=[('DR', 'Draft'), ('RV', 'Review'), ('AP', 'Approved'), ('RJ', 'Rejected')], help_text='policy status', max_length=2)),
                ('deductible_amount', models.DecimalField(decimal_places=2, help_text='amount that is deducted', max_digits=10)),
                ('claim_amount_approved', models.DecimalField(decimal_places=2, help_text='amount apprvoed in claim', max_digits=10)),
                ('submission_date', models.DateTimeField(auto_now_add=True)),
                ('incident_description', models.TextField(help_text='detail about incident', max_length=500)),
                ('estimated_repair_cost', models.DecimalField(decimal_places=2, help_text='total repair cost', max_digits=10)),
                ('customer_policy', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='claims', to='insurance_app.customer_policy')),
            ],
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='your device name', max_length=100)),
                ('brand', models.CharField(choices=[('Apple', 'Apple'), ('Google', 'Google'), ('Samsung', 'Samsung'), ('OnePlus', 'OnePlus')], default='Apple', help_text='device brand name', max_length=50)),
                ('model', models.CharField(help_text='your device model like iphone 15 pro ', max_length=50)),
                ('purchase_date', models.DateField()),
                ('imei_number', models.CharField(help_text='enter your mobile IMEI number', max_length=50, unique=True)),
                ('user', models.ForeignKey(help_text='the owner details', on_delete=django.db.models.deletion.CASCADE, related_name='devices', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='customer_policy',
            name='device',
            field=models.ForeignKey(help_text='specific mobile device cover', on_delete=django.db.models.deletion.PROTECT, related_name='coverage_contracts', to='insurance_app.device'),
        ),
        migrations.AddField(
            model_name='customer_policy',
            name='policy',
            field=models.ForeignKey(help_text='policy belongs to this customer', on_delete=django.db.models.deletion.PROTECT, related_name='purchased_policies', to='insurance_app.policy'),
        ),
    ]
